//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HizliSatis
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gider
    {
        public int GiderId { get; set; }
        public string GiderAdi { get; set; }
        public Nullable<decimal> Toplam { get; set; }
    }
}
