//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HizliSatis
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class hizlisatisEntities4 : DbContext
    {
        public hizlisatisEntities4()
            : base("name=hizlisatisEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Gider> Giders { get; set; }
        public virtual DbSet<Kullanicilar> Kullanicilars { get; set; }
        public virtual DbSet<Satislar> Satislars { get; set; }
        public virtual DbSet<UrunGruplari> UrunGruplaris { get; set; }
        public virtual DbSet<Urunler> Urunlers { get; set; }
    
        public virtual ObjectResult<gunlukciro_Result> gunlukciro(Nullable<System.DateTime> tarih)
        {
            var tarihParameter = tarih.HasValue ?
                new ObjectParameter("tarih", tarih) :
                new ObjectParameter("tarih", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<gunlukciro_Result>("gunlukciro", tarihParameter);
        }
    
        public virtual ObjectResult<tariharasisatisciro_Result> tariharasisatisciro(Nullable<System.DateTime> tarih1, Nullable<System.DateTime> tarih2)
        {
            var tarih1Parameter = tarih1.HasValue ?
                new ObjectParameter("tarih1", tarih1) :
                new ObjectParameter("tarih1", typeof(System.DateTime));
    
            var tarih2Parameter = tarih2.HasValue ?
                new ObjectParameter("tarih2", tarih2) :
                new ObjectParameter("tarih2", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tariharasisatisciro_Result>("tariharasisatisciro", tarih1Parameter, tarih2Parameter);
        }
    
        public virtual ObjectResult<tariharasisatislar_Result> tariharasisatislar(Nullable<System.DateTime> tarih1, Nullable<System.DateTime> tarih2)
        {
            var tarih1Parameter = tarih1.HasValue ?
                new ObjectParameter("tarih1", tarih1) :
                new ObjectParameter("tarih1", typeof(System.DateTime));
    
            var tarih2Parameter = tarih2.HasValue ?
                new ObjectParameter("tarih2", tarih2) :
                new ObjectParameter("tarih2", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tariharasisatislar_Result>("tariharasisatislar", tarih1Parameter, tarih2Parameter);
        }
    }
}
