//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HizliSatis
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class hizlisatisEntities3 : DbContext
    {
        public hizlisatisEntities3()
            : base("name=hizlisatisEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Gider> Giders { get; set; }
        public virtual DbSet<Kullanicilar> Kullanicilars { get; set; }
        public virtual DbSet<Satislar> Satislars { get; set; }
        public virtual DbSet<SatisListesi> SatisListesis { get; set; }
        public virtual DbSet<UrunGruplari> UrunGruplaris { get; set; }
        public virtual DbSet<Urunler> Urunlers { get; set; }
    
        public virtual ObjectResult<ikitariharasiSatislar_Result> ikitariharasiSatislar(Nullable<System.DateTime> tarih1, Nullable<System.DateTime> tarih2)
        {
            var tarih1Parameter = tarih1.HasValue ?
                new ObjectParameter("tarih1", tarih1) :
                new ObjectParameter("tarih1", typeof(System.DateTime));
    
            var tarih2Parameter = tarih2.HasValue ?
                new ObjectParameter("tarih2", tarih2) :
                new ObjectParameter("tarih2", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ikitariharasiSatislar_Result>("ikitariharasiSatislar", tarih1Parameter, tarih2Parameter);
        }
    
        public virtual ObjectResult<Nullable<double>> ikitariharasiSatislarToplami(Nullable<System.DateTime> tarih1, Nullable<System.DateTime> tarih2)
        {
            var tarih1Parameter = tarih1.HasValue ?
                new ObjectParameter("tarih1", tarih1) :
                new ObjectParameter("tarih1", typeof(System.DateTime));
    
            var tarih2Parameter = tarih2.HasValue ?
                new ObjectParameter("tarih2", tarih2) :
                new ObjectParameter("tarih2", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("ikitariharasiSatislarToplami", tarih1Parameter, tarih2Parameter);
        }
    
        public virtual ObjectResult<Nullable<double>> ikitariharasisatistoplami(Nullable<System.DateTime> tarih1, Nullable<System.DateTime> tarih2)
        {
            var tarih1Parameter = tarih1.HasValue ?
                new ObjectParameter("tarih1", tarih1) :
                new ObjectParameter("tarih1", typeof(System.DateTime));
    
            var tarih2Parameter = tarih2.HasValue ?
                new ObjectParameter("tarih2", tarih2) :
                new ObjectParameter("tarih2", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("ikitariharasisatistoplami", tarih1Parameter, tarih2Parameter);
        }
    
        public virtual ObjectResult<SatisIDBySatisListesi_Result> SatisIDBySatisListesi(Nullable<int> satisId)
        {
            var satisIdParameter = satisId.HasValue ?
                new ObjectParameter("SatisId", satisId) :
                new ObjectParameter("SatisId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SatisIDBySatisListesi_Result>("SatisIDBySatisListesi", satisIdParameter);
        }
    
        public virtual ObjectResult<TARIHIGecenUrunListesi_Result> TARIHIGecenUrunListesi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TARIHIGecenUrunListesi_Result>("TARIHIGecenUrunListesi");
        }
    
        public virtual ObjectResult<TARIHsatisListesi_Result> TARIHsatisListesi(Nullable<System.DateTime> tarih1, Nullable<System.DateTime> tarih2)
        {
            var tarih1Parameter = tarih1.HasValue ?
                new ObjectParameter("tarih1", tarih1) :
                new ObjectParameter("tarih1", typeof(System.DateTime));
    
            var tarih2Parameter = tarih2.HasValue ?
                new ObjectParameter("tarih2", tarih2) :
                new ObjectParameter("tarih2", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TARIHsatisListesi_Result>("TARIHsatisListesi", tarih1Parameter, tarih2Parameter);
        }
    
        public virtual ObjectResult<Nullable<double>> TARIHsatisListesiGider(Nullable<System.DateTime> tarih1, Nullable<System.DateTime> tarih2)
        {
            var tarih1Parameter = tarih1.HasValue ?
                new ObjectParameter("tarih1", tarih1) :
                new ObjectParameter("tarih1", typeof(System.DateTime));
    
            var tarih2Parameter = tarih2.HasValue ?
                new ObjectParameter("tarih2", tarih2) :
                new ObjectParameter("tarih2", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("TARIHsatisListesiGider", tarih1Parameter, tarih2Parameter);
        }
    
        public virtual ObjectResult<Nullable<double>> TARIHsatisListesiToplami(Nullable<System.DateTime> tarih1, Nullable<System.DateTime> tarih2)
        {
            var tarih1Parameter = tarih1.HasValue ?
                new ObjectParameter("tarih1", tarih1) :
                new ObjectParameter("tarih1", typeof(System.DateTime));
    
            var tarih2Parameter = tarih2.HasValue ?
                new ObjectParameter("tarih2", tarih2) :
                new ObjectParameter("tarih2", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("TARIHsatisListesiToplami", tarih1Parameter, tarih2Parameter);
        }
    
        public virtual ObjectResult<tarihigecenler_Result> tarihigecenler()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tarihigecenler_Result>("tarihigecenler");
        }
    }
}
