//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HizliSatis
{
    using System;
    using System.Collections.Generic;
    
    public partial class Satislar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Satislar()
        {
            this.SatisListesis = new HashSet<SatisListesi>();
        }
    
        public int SatisId { get; set; }
        public string OdemeTuru { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<double> ToplamTutar { get; set; }
        public Nullable<double> ToplamKDV { get; set; }
        public Nullable<double> NetToplam { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SatisListesi> SatisListesis { get; set; }
    }
}
