//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HizliSatis
{
    using System;
    using System.Collections.Generic;
    
    public partial class SatisListesi
    {
        public int SatislistID { get; set; }
        public Nullable<int> UrunID { get; set; }
        public Nullable<int> SatisId { get; set; }
        public Nullable<int> Miktar { get; set; }
        public Nullable<double> Birimfiyat { get; set; }
        public Nullable<double> Kdv { get; set; }
        public Nullable<double> BirimToplamTutar { get; set; }
        public Nullable<double> KdvTutari { get; set; }
        public Nullable<double> NetTutar { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    
        public virtual Satislar Satislar { get; set; }
        public virtual Urunler Urunler { get; set; }
    }
}
