//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HizliSatis
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urunler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Urunler()
        {
            this.SatisListesis = new HashSet<SatisListesi>();
        }
    
        public int UrunId { get; set; }
        public string UrunAdi { get; set; }
        public Nullable<double> AlisFiyati { get; set; }
        public Nullable<double> SatisFiyat { get; set; }
        public string Gorsel { get; set; }
        public Nullable<double> Kdv { get; set; }
        public Nullable<System.DateTime> UretimTarihi { get; set; }
        public Nullable<System.DateTime> Rafomru { get; set; }
        public Nullable<int> GrupId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SatisListesi> SatisListesis { get; set; }
        public virtual UrunGruplari UrunGruplari { get; set; }
    }
}
